export const quizData = [
    {
        key: 1,
        question: "1",
        options: ["A", "B", "C", "D"],
        correctAnswer: "C",
    },
    {
        key: 2,
        question: "2",
        options: ["A", "B", "C", "D"],
        correctAnswer: "B",
    },
    {
        key: 3,
        question: "3",
        options: ["A", "B", "C", "D"],
        correctAnswer: "D",
    },
    {
        key: 4,
        question: "4",
        options: ["A", "B", "C", "D"],
        correctAnswer: "A",
    },
    {
        key: 5,
        question: "5",
        options: ["A", "B", "C", "D"],
        correctAnswer: "B",
    },
    {
        key: 6,
        question: "6",
        options: ["A", "B", "C", "D"],
        correctAnswer: "C",
    },
    {
        key: 7,
        question: "7",
        options: ["A", "B", "C", "D"],
        correctAnswer: "D",
    },
    {
        key: 8,
        question: "8",
        options: ["A", "B", "C", "D"],
        correctAnswer: "A",
    },
    {
        key: 9,
        question: "9",
        options: ["A", "B", "C", "D"],
        correctAnswer: "B",
    },
    {
        key: 10,
        question: "10",
        options: ["A", "B", "C", "D"],
        correctAnswer: "C",
    },
    {
        key: 11,
        question: "11",
        options: ["A", "B", "C", "D"],
        correctAnswer: "D",
    },
    {
        key: 12,
        question: "12",
        options: ["A", "B", "C", "D"],
        correctAnswer: "A",
    },
    {
        key: 13,
        question: "13",
        options: ["A", "B", "C", "D"],
        correctAnswer: "B",
    },
    {
        key: 14,
        question: "14",
        options: ["A", "B", "C", "D"],
        correctAnswer: "C",
    },
    {
        key: 15,
        question: "15",
        options: ["A", "B", "C", "D"],
        correctAnswer: "D",
    },
    {
        key: 16,
        question: "16",
        options: ["A", "B", "C", "D"],
        correctAnswer: "A",
    },
    {
        key: 17,
        question: "17",
        options: ["A", "B", "C", "D"],
        correctAnswer: "B",
    },
    {
        key: 18,
        question: "18",
        options: ["A", "B", "C", "D"],
        correctAnswer: "C",
    },
    {
        key: 19,
        question: "19",
        options: ["A", "B", "C", "D"],
        correctAnswer: "D",
    },
    {
        key: 20,
        question: "20",
        options: ["A", "B", "C", "D"],
        correctAnswer: "A",
    },
];